import { NextRequest, NextResponse } from "next/server";
import yaml from "js-yaml";
import type { Stage5Output } from "@/lib/pipeline/schemas";

export const runtime = "nodejs";

export async function POST(req: NextRequest) {
  try {
    const { result }: { result: Stage5Output } = await req.json();

    if (!result) {
      return NextResponse.json({ error: "Missing result" }, { status: 400 });
    }

    const { intent, schemas } = result.masterConfig;
    const { apiSchema, authSchema } = schemas;

    // Build OpenAPI 3.1 spec
    const openApiSpec: Record<string, unknown> = {
      openapi: "3.1.0",
      info: {
        title: intent.appName,
        description: intent.tagline,
        version: "1.0.0",
        contact: {
          name: "Generated by AppCompiler",
        },
      },
      servers: [
        {
          url: apiSchema.baseUrl,
          description: "Production server",
        },
        {
          url: "http://localhost:3000/api/v1",
          description: "Local development",
        },
      ],
      tags: [...new Set(
        apiSchema.endpoints.map(e => {
          const parts = e.path.split("/").filter(Boolean);
          return parts[1] || "general"; // e.g. /api/v1/users → users
        })
      )].map(name => ({ name, description: `${name} operations` })),
      paths: buildPaths(apiSchema.endpoints),
      components: {
        securitySchemes: buildSecuritySchemes(authSchema.provider),
        schemas: buildComponentSchemas(schemas.dbSchema.tables),
      },
      security: authSchema.provider === "JWT"
        ? [{ bearerAuth: [] }]
        : authSchema.provider === "OAuth"
        ? [{ oauth2: [] }]
        : [{ bearerAuth: [] }, { oauth2: [] }],
    };

    const yamlString = yaml.dump(openApiSpec, {
      indent: 2,
      lineWidth: 120,
      noRefs: true,
    });

    return new NextResponse(yamlString, {
      headers: {
        "Content-Type": "application/yaml",
        "Content-Disposition": `attachment; filename="${intent.appName.replace(/\s+/g, "-").toLowerCase()}-openapi.yaml"`,
      },
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Export failed";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}

function buildPaths(endpoints: Stage5Output["masterConfig"]["schemas"]["apiSchema"]["endpoints"]): Record<string, unknown> {
  const paths: Record<string, Record<string, unknown>> = {};

  for (const endpoint of endpoints) {
    // Convert /api/v1/users/:id → /api/v1/users/{id}
    const normalizedPath = endpoint.path.replace(/:(\w+)/g, "{$1}");

    if (!paths[normalizedPath]) {
      paths[normalizedPath] = {};
    }

    const method = endpoint.method.toLowerCase();
    const pathParams = [...endpoint.path.matchAll(/:(\w+)/g)].map(m => m[1]);

    const operation: Record<string, unknown> = {
      summary: endpoint.summary,
      description: endpoint.description,
      operationId: endpoint.id,
      tags: [normalizedPath.split("/").filter(Boolean)[2] || "general"],
      security: endpoint.requiredRoles.length > 0 ? [{ bearerAuth: [] }] : [],
      responses: {
        "200": {
          description: "Success",
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: endpoint.responseBody.successSchema,
              },
            },
          },
        },
        "400": {
          description: "Bad Request",
          content: {
            "application/json": {
              schema: { $ref: "#/components/schemas/Error" },
            },
          },
        },
        "401": {
          description: "Unauthorized",
        },
        "403": {
          description: "Forbidden",
        },
        "500": {
          description: "Internal Server Error",
          content: {
            "application/json": {
              schema: { $ref: "#/components/schemas/Error" },
            },
          },
        },
      },
    };

    // Path parameters
    if (pathParams.length > 0) {
      operation.parameters = pathParams.map(param => ({
        name: param,
        in: "path",
        required: true,
        schema: { type: "string" },
        description: `The ${param} identifier`,
      }));
    }

    // Query parameters
    if (endpoint.queryParams && endpoint.queryParams.length > 0) {
      const existing = (operation.parameters as unknown[]) || [];
      operation.parameters = [
        ...existing,
        ...endpoint.queryParams.map(qp => ({
          name: qp.name,
          in: "query",
          required: qp.required,
          schema: { type: qp.type },
          description: qp.description,
        })),
      ];
    }

    // Request body
    if (endpoint.requestBody && endpoint.requestBody.fields.length > 0) {
      const properties: Record<string, unknown> = {};
      const required: string[] = [];

      for (const field of endpoint.requestBody.fields) {
        properties[field.name] = {
          type: mapType(field.type),
          description: field.validation || undefined,
        };
        if (field.required) required.push(field.name);
      }

      operation.requestBody = {
        required: true,
        content: {
          "application/json": {
            schema: {
              type: "object",
              properties,
              required: required.length > 0 ? required : undefined,
            },
          },
        },
      };
    }

    // Rate limiting as extension
    if (endpoint.rateLimit) {
      operation["x-rate-limit"] = endpoint.rateLimit;
    }

    // Required roles as extension
    if (endpoint.requiredRoles.length > 0) {
      operation["x-required-roles"] = endpoint.requiredRoles;
    }

    paths[normalizedPath][method] = operation;
  }

  return paths;
}

function buildSecuritySchemes(provider: string): Record<string, unknown> {
  const schemes: Record<string, unknown> = {};

  if (provider === "JWT" || provider === "both") {
    schemes.bearerAuth = {
      type: "http",
      scheme: "bearer",
      bearerFormat: "JWT",
      description: "JWT access token",
    };
  }

  if (provider === "OAuth" || provider === "both") {
    schemes.oauth2 = {
      type: "oauth2",
      flows: {
        authorizationCode: {
          authorizationUrl: "/api/v1/auth/oauth/authorize",
          tokenUrl: "/api/v1/auth/oauth/token",
          scopes: {
            read: "Read access",
            write: "Write access",
            admin: "Admin access",
          },
        },
      },
    };
  }

  return schemes;
}

function buildComponentSchemas(
  tables: Stage5Output["masterConfig"]["schemas"]["dbSchema"]["tables"]
): Record<string, unknown> {
  const schemas: Record<string, unknown> = {
    Error: {
      type: "object",
      properties: {
        error: { type: "string" },
        message: { type: "string" },
        statusCode: { type: "integer" },
      },
      required: ["error", "message"],
    },
    Pagination: {
      type: "object",
      properties: {
        page: { type: "integer", minimum: 1 },
        pageSize: { type: "integer", minimum: 1, maximum: 100 },
        total: { type: "integer" },
        totalPages: { type: "integer" },
      },
    },
  };

  for (const table of tables) {
    const properties: Record<string, unknown> = {};
    const required: string[] = [];

    for (const col of table.columns) {
      properties[col.name] = {
        type: mapDbType(col.type),
        description: col.foreignKey
          ? `Foreign key → ${col.foreignKey.table}.${col.foreignKey.column}`
          : undefined,
        nullable: col.nullable || undefined,
        readOnly: col.name === "id" || col.name === "created_at" || col.name === "updated_at" || undefined,
      };

      if (!col.nullable && !col.default && col.name !== "id") {
        required.push(col.name);
      }
    }

    // Convert snake_case table name to PascalCase schema name
    const schemaName = table.name
      .split("_")
      .map(w => w.charAt(0).toUpperCase() + w.slice(1))
      .join("");

    schemas[schemaName] = {
      type: "object",
      description: table.description,
      properties,
      required: required.length > 0 ? required : undefined,
    };
  }

  return schemas;
}

function mapType(type: string): string {
  const t = type.toLowerCase();
  if (t.includes("int") || t.includes("number")) return "integer";
  if (t.includes("float") || t.includes("decimal") || t.includes("double")) return "number";
  if (t.includes("bool")) return "boolean";
  if (t.includes("array") || t.includes("[]")) return "array";
  if (t.includes("object") || t.includes("{}")) return "object";
  return "string";
}

function mapDbType(type: string): string {
  const t = type.toLowerCase();
  if (t.includes("int") || t.includes("serial") || t.includes("bigint")) return "integer";
  if (t.includes("float") || t.includes("decimal") || t.includes("numeric") || t.includes("real")) return "number";
  if (t.includes("bool")) return "boolean";
  if (t.includes("json") || t.includes("jsonb")) return "object";
  if (t.includes("array") || t.includes("[]")) return "array";
  return "string";
}
